# Generated by Django 3.0.5 on 2020-05-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFeedbackMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('report_id', models.CharField(blank=True, max_length=255, null=True)),
                ('begin', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('adkim', models.CharField(blank=True, max_length=255, null=True)),
                ('aspf', models.CharField(blank=True, max_length=255, null=True)),
                ('p', models.CharField(blank=True, max_length=255, null=True)),
                ('sp', models.CharField(blank=True, max_length=255, null=True)),
                ('pct', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfmd_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfmd_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfmd_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Report_Feedback_MetaData',
            },
        ),
        migrations.CreateModel(
            name='ReportFeedbackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('dkim', models.CharField(blank=True, max_length=255, null=True)),
                ('spf', models.CharField(blank=True, max_length=255, null=True)),
                ('header_from', models.CharField(blank=True, max_length=255, null=True)),
                ('envelope_from', models.CharField(blank=True, max_length=255, null=True)),
                ('dkim_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('dkim_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('dkim_result', models.CharField(blank=True, max_length=255, null=True)),
                ('spf_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('spf_scope', models.CharField(blank=True, max_length=255, null=True)),
                ('spf_result', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfr_created_by', to=settings.AUTH_USER_MODEL)),
                ('meta_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ReportFeedbackMetaData')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfr_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfr_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Report_Feedback_Record',
            },
        ),
        migrations.CreateModel(
            name='ReportDumpUploadbkp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdlb_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdlb_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdlb_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Report_Dump_Upload_bkp',
            },
        ),
    ]
