# Generated by Django 3.0.5 on 2020-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200511_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfeedbackrecord',
            name='ip_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
