# Generated by Django 3.0.5 on 2020-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_menu_role_rolemenumappingtable_roleusermappingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
