# Generated by Django 3.0.5 on 2020-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200527_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='is_create',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='is_edit',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='is_read',
        ),
        migrations.AddField(
            model_name='role',
            name='is_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
