# Generated by Django 3.0.5 on 2020-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200529_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='menu',
        ),
        migrations.AddField(
            model_name='rolemenumappingtable',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='core.Menu'),
        ),
    ]
