# Generated by Django 3.0.5 on 2020-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200601_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_execute',
            field=models.BooleanField(default=False),
        ),
    ]
