# Generated by Django 3.0.5 on 2020-06-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_role_is_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
