# Generated by Django 3.0.5 on 2020-06-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_role_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_Admin',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_create',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_edit',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_execute',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_read',
        ),
    ]
