# Generated by Django 3.0.5 on 2020-06-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mailtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailTemplate',
        ),
    ]
