# Generated by Django 3.0.7 on 2020-06-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_mailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleacessmappingtable',
            name='access',
        ),
        migrations.RemoveField(
            model_name='roleacessmappingtable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='roleacessmappingtable',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='roleacessmappingtable',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleacessmappingtable',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolemenumappingtable',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_Admin',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_email_only',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_finance_billing_only',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_finance_delete',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_finance_edit',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_finance_execute',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_finance_read',
        ),
        migrations.RemoveField(
            model_name='access',
            name='is_finance_write',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='RoleAcessMappingTable',
        ),
        migrations.DeleteModel(
            name='RoleMenuMappingTable',
        ),
    ]
