# Generated by Django 3.0.7 on 2020-06-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_childmenu_parentmenu_roleparentmenuacessmappingtable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': '6. Access'},
        ),
        migrations.AlterModelOptions(
            name='childmenu',
            options={'verbose_name_plural': '4. Child Menu'},
        ),
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'verbose_name_plural': '14. Mail Template'},
        ),
        migrations.AlterModelOptions(
            name='parentmenu',
            options={'verbose_name_plural': '3. Parent Menu'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '1. profile'},
        ),
        migrations.AlterModelOptions(
            name='reportdumpuploadbkp',
            options={'verbose_name_plural': '9. Report Dump Upload bkp'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackmetadata',
            options={'verbose_name_plural': '10. Report Feedback MetaData'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackrecord',
            options={'verbose_name_plural': '11. Report Feedback Record'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackrecordauthresultsdkim',
            options={'verbose_name_plural': '12. Report Feedback Record Auth Results Dkim'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackrecordauthresultsspf',
            options={'verbose_name_plural': '13. Report Feedback Record Auth Results Spf'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '5. Role'},
        ),
        migrations.AlterModelOptions(
            name='roleparentmenuacessmappingtable',
            options={'verbose_name_plural': '7. Role Parent Menu Access mapping table'},
        ),
        migrations.AlterModelOptions(
            name='roleusermappingtable',
            options={'verbose_name_plural': '8. Role user mapping table'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name_plural': '2. Tenant'},
        ),
    ]
