# Generated by Django 3.0.7 on 2020-06-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200609_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': 'Access'},
        ),
        migrations.AlterModelOptions(
            name='childmenu',
            options={'verbose_name_plural': 'Child Menu'},
        ),
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'verbose_name_plural': 'Mail Template'},
        ),
        migrations.AlterModelOptions(
            name='parentmenu',
            options={'verbose_name_plural': 'Parent Menu'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile'},
        ),
        migrations.AlterModelOptions(
            name='reportdumpuploadbkp',
            options={'verbose_name_plural': 'Report Dump Upload bkp'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackmetadata',
            options={'verbose_name_plural': 'Report Feedback MetaData'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackrecord',
            options={'verbose_name_plural': 'Report Feedback Record'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackrecordauthresultsdkim',
            options={'verbose_name_plural': 'Report Feedback Record Auth Results Dkim'},
        ),
        migrations.AlterModelOptions(
            name='reportfeedbackrecordauthresultsspf',
            options={'verbose_name_plural': 'Report Feedback Record Auth Results Spf'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='roleparentmenuacessmappingtable',
            options={'verbose_name_plural': 'Role Parent Menu Access mapping table'},
        ),
        migrations.AlterModelOptions(
            name='roleusermappingtable',
            options={'verbose_name_plural': 'Role user mapping table'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name_plural': 'Tenant'},
        ),
    ]
