# Generated by Django 3.0.5 on 2020-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200504_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdumpuploadbkp',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
