# Generated by Django 3.0.5 on 2020-05-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profie',
        ),
    ]
