# Generated by Django 3.0.5 on 2020-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reportfeedbackrecord_ip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfeedbackrecord',
            name='count',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
