# Generated by Django 3.0.5 on 2020-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_access_roleacessmappingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleacessmappingtable',
            name='access',
            field=models.ManyToManyField(blank=True, to='core.Access'),
        ),
        migrations.AlterField(
            model_name='rolemenumappingtable',
            name='menu',
            field=models.ManyToManyField(blank=True, to='core.Menu'),
        ),
    ]
