apiVersion: v1
kind: Service
metadata:
  name: brandsecure-backend
  namespace: secureyourinbox
  labels:
    app: brandsecure-backend
spec:
  type: ClusterIP
  ports:
    - name: brandsecure-backend
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: brandsecure-backend
