apiVersion: apps/v1
kind: Deployment
metadata:
  name: brandsecure-backend
  namespace: secureyourinbox
  labels:
    app: brandsecure-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brandsecure-backend
  template:
    metadata:
      labels:
        app: brandsecure-backend
    spec:
      imagePullSecrets:
      - name: dockerhub 
      containers:
      - name: brandsecure-backend
        image: secureyourinbox/brandsecure
        imagePullPolicy: Always
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8000
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 8000
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: brandsecure-backend-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
             name: brandsecure-backend-secrets
             key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
             name: brandsecure-backend-secrets
             key: SECRET_KEY
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
             name: brandsecure-backend-secrets
             key: SENDGRID_API_KEY
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: brandsecure-backend-configmap
              key: DB_HOST
        - name: DB_PORT 
          valueFrom:
            configMapKeyRef:
              name: brandsecure-backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: brandsecure-backend-configmap
              key: DB_NAME
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: brandsecure-backend-configmap
              key: DEBUG
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: brandsecure-backend-configmap
              key: DJANGO_ALLOWED_HOSTS
        - name: DB_ENGINE
          valueFrom:
            configMapKeyRef:
              name: brandsecure-backend-configmap           
              key: DB_ENGINE
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "1024Mi"
