apiVersion: v1
kind: Secret
metadata:
  name: brandsecure-backend-secrets
  namespace: secureyourinbox
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: WUx1TVRIZmdsMkNGZ29MQ1VtQ00=
  SECRET_KEY: YS1lI3Z0JCU1NjlKTlJYZ2hpa2xzPTMwZCtkXjEtOWRnNGVraGg0XmkpXmMzdXlxdw==
  SENDGRID_API_KEY: U0cuOURHM3F0ZHlRUzZPNWlLRHhsMzhNZy5Id3p1OEN4Z3duV2VfblZnS3V6UDlGQXRTUEFVbEVJZGx6NjhNdnIzTU93
